name: Welcome to the Microsoft Generative AI
on:
  # Trigger the workflow on pull request
  pull_request_target:
    types: [opened]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  assess-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label and thanks comment to Pull request
        uses: actions/github-script@v6
        with:
          script: |
            const issueAuthor = context.payload.sender.login
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-review']
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ðŸ‘‹ Thanks for contributing @${ issueAuthor }! We will review the pull request and get back to you soon.`
            })
      - name: Log PR Details
        run: |
          echo "Reviewers: ${{ github.event.pull_request.requested_reviewers }}"
          echo "Assignees: ${{ github.event.pull_request.assignees }}"
      - name: Auto-assign PR
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number
            const assignees = ['koreyspace']
            const reviewers = ['koreyspace']

            // Add assignees
            await github.rest.issues.addAssignees({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: assignees
            })

            // Request reviewers
            await github.rest.pulls.requestReviewers({
              pull_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: reviewers
            })
